/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestion_usuarios;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author accpm
 */
public class CRUD_Gimnasio1 extends javax.swing.JFrame {
    
    
    
    int largoCamara = 340;
    int anchoCamara = 310; 
            
            Dimension dimension = new Dimension(largoCamara, anchoCamara);
            Dimension dimension1 = WebcamResolution.VGA.getSize();
            Webcam webcam = Webcam.getDefault();
            WebcamPanel webcamPanel = new WebcamPanel(webcam,dimension,false);
            
            BufferedImage ruta;
            int contador = 0;

    private boolean maximizado = false;
    int xMouse, yMouse;

    public CRUD_Gimnasio1() {
        initComponents();
        
        UsuarioGimnasio g = new UsuarioGimnasio();
        g.MostrarUsuarios(Tabla1);
        
        webcam.setViewSize(dimension1);
        webcamPanel.setFillArea(true);
        pnlCamara.setLayout(new FlowLayout());
        pnlCamara.add(webcamPanel);
        lblNombreCamara.setText(webcam.toString());
        
        ApagarBotones();
    }
    
    public void ApagarBotones() {
        lapagar.setEnabled(false);
        lcapturar.setEnabled(false);
        lguardar.setEnabled(false);

    }

    public void PrenderBotones() {
        lapagar.setEnabled(true);
        lcapturar.setEnabled(true);
    }
    
    public void textoBotonesCuandoCargaCamara(){
        iniciar.setText("Iniciando camara...");
        apagar.setText("Iniciando camara...");
        capturar.setText("Iniciando camara...");
        guardar.setText("Iniciando camara...");
    }
    
    public void textoBotonesCuandoCargoCamara(){
        iniciar.setText("INICIAR");
        apagar.setText("APAGAR");
        capturar.setText("CAPTURAR");
        guardar.setText("GUARDAR");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelmpusuarios = new javax.swing.JPanel();
        panelsalirusuarios = new javax.swing.JPanel();
        btnMaximizarusuarios = new javax.swing.JPanel();
        Maximizarusuarios = new javax.swing.JLabel();
        btnSalirusuarios = new javax.swing.JPanel();
        Salirusuarios = new javax.swing.JLabel();
        btnMinimizarusuarios = new javax.swing.JPanel();
        Minimizarusuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnNombre15 = new javax.swing.JPanel();
        Nombre15 = new javax.swing.JLabel();
        TextId = new javax.swing.JTextField();
        btnNombre = new javax.swing.JPanel();
        Nombre = new javax.swing.JLabel();
        TextPNombre = new javax.swing.JTextField();
        btnNombre1 = new javax.swing.JPanel();
        Nombre1 = new javax.swing.JLabel();
        TextSNombre = new javax.swing.JTextField();
        btnNombre2 = new javax.swing.JPanel();
        Nombre2 = new javax.swing.JLabel();
        TextTNombre = new javax.swing.JTextField();
        btnNombre3 = new javax.swing.JPanel();
        Nombre3 = new javax.swing.JLabel();
        TextPApellido = new javax.swing.JTextField();
        btnNombre4 = new javax.swing.JPanel();
        Nombre4 = new javax.swing.JLabel();
        TextSApellido = new javax.swing.JTextField();
        btnNombre5 = new javax.swing.JPanel();
        Nombre5 = new javax.swing.JLabel();
        TextTelefono = new javax.swing.JTextField();
        btnNombre6 = new javax.swing.JPanel();
        Nombre6 = new javax.swing.JLabel();
        TextCorreo = new javax.swing.JTextField();
        btnNombre11 = new javax.swing.JPanel();
        Nombre11 = new javax.swing.JLabel();
        JFechaNacimiento = new com.toedter.calendar.JDateChooser();
        btnNombre7 = new javax.swing.JPanel();
        Nombre7 = new javax.swing.JLabel();
        TextPENombre = new javax.swing.JTextField();
        btnNombre8 = new javax.swing.JPanel();
        Nombre8 = new javax.swing.JLabel();
        TextPEApellido = new javax.swing.JTextField();
        btnNombre9 = new javax.swing.JPanel();
        Nombre9 = new javax.swing.JLabel();
        TextParentesco = new javax.swing.JTextField();
        btnNombre16 = new javax.swing.JPanel();
        Nombre16 = new javax.swing.JLabel();
        TextTelefonoPE = new javax.swing.JTextField();
        btnNombre13 = new javax.swing.JPanel();
        Nombre13 = new javax.swing.JLabel();
        JFechaPago = new com.toedter.calendar.JDateChooser();
        btnNombre12 = new javax.swing.JPanel();
        Nombre12 = new javax.swing.JLabel();
        JFechaIngreso = new com.toedter.calendar.JDateChooser();
        btnNombre10 = new javax.swing.JPanel();
        Nombre10 = new javax.swing.JLabel();
        pnlCamara = new javax.swing.JPanel();
        panelfoto = new javax.swing.JPanel();
        fotousuario = new javax.swing.JLabel();
        btnNombre14 = new javax.swing.JPanel();
        Nombre14 = new javax.swing.JLabel();
        Buscar = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificarl = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla1 = new javax.swing.JTable();
        btniniciar = new javax.swing.JPanel();
        iniciar = new javax.swing.JLabel();
        btnliniciar = new javax.swing.JPanel();
        liniciar = new javax.swing.JLabel();
        btnapagar = new javax.swing.JPanel();
        apagar = new javax.swing.JLabel();
        btnlapagar = new javax.swing.JPanel();
        lapagar = new javax.swing.JLabel();
        btncapturar = new javax.swing.JPanel();
        capturar = new javax.swing.JLabel();
        btnlcapturar = new javax.swing.JPanel();
        lcapturar = new javax.swing.JLabel();
        btnguardar = new javax.swing.JPanel();
        guardar = new javax.swing.JLabel();
        btnlguardar = new javax.swing.JPanel();
        lguardar = new javax.swing.JLabel();
        lblNombreCamara = new javax.swing.JLabel();
        TextFoto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelmpusuarios.setBackground(new java.awt.Color(0, 0, 0));
        panelmpusuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelsalirusuarios.setBackground(new java.awt.Color(255, 255, 255));
        panelsalirusuarios.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelsalirusuariosMouseDragged(evt);
            }
        });
        panelsalirusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelsalirusuariosMousePressed(evt);
            }
        });

        btnMaximizarusuarios.setBackground(new java.awt.Color(255, 255, 255));

        Maximizarusuarios.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        Maximizarusuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Maximizarusuarios.setText("□");
        Maximizarusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaximizarusuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaximizarusuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaximizarusuariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMaximizarusuariosLayout = new javax.swing.GroupLayout(btnMaximizarusuarios);
        btnMaximizarusuarios.setLayout(btnMaximizarusuariosLayout);
        btnMaximizarusuariosLayout.setHorizontalGroup(
            btnMaximizarusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Maximizarusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );
        btnMaximizarusuariosLayout.setVerticalGroup(
            btnMaximizarusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Maximizarusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        btnSalirusuarios.setBackground(new java.awt.Color(255, 255, 255));

        Salirusuarios.setFont(new java.awt.Font("Microsoft Yi Baiti", 1, 12)); // NOI18N
        Salirusuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salirusuarios.setText("X");
        Salirusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalirusuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalirusuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalirusuariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnSalirusuariosLayout = new javax.swing.GroupLayout(btnSalirusuarios);
        btnSalirusuarios.setLayout(btnSalirusuariosLayout);
        btnSalirusuariosLayout.setHorizontalGroup(
            btnSalirusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Salirusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );
        btnSalirusuariosLayout.setVerticalGroup(
            btnSalirusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Salirusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        btnMinimizarusuarios.setBackground(new java.awt.Color(255, 255, 255));

        Minimizarusuarios.setFont(new java.awt.Font("Segoe UI Light", 1, 24)); // NOI18N
        Minimizarusuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Minimizarusuarios.setText("-\n");
        Minimizarusuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MinimizarusuariosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MinimizarusuariosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MinimizarusuariosMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnMinimizarusuariosLayout = new javax.swing.GroupLayout(btnMinimizarusuarios);
        btnMinimizarusuarios.setLayout(btnMinimizarusuariosLayout);
        btnMinimizarusuariosLayout.setHorizontalGroup(
            btnMinimizarusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Minimizarusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
        );
        btnMinimizarusuariosLayout.setVerticalGroup(
            btnMinimizarusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Minimizarusuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelsalirusuariosLayout = new javax.swing.GroupLayout(panelsalirusuarios);
        panelsalirusuarios.setLayout(panelsalirusuariosLayout);
        panelsalirusuariosLayout.setHorizontalGroup(
            panelsalirusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelsalirusuariosLayout.createSequentialGroup()
                .addGap(0, 1437, Short.MAX_VALUE)
                .addComponent(btnMinimizarusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnMaximizarusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalirusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelsalirusuariosLayout.setVerticalGroup(
            panelsalirusuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnSalirusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMaximizarusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btnMinimizarusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelmpusuarios.add(panelsalirusuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1540, -1));

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESAR DATOS DEL CLIENTE");
        jLabel1.setToolTipText("");
        panelmpusuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1530, 70));

        btnNombre15.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre15.setForeground(new java.awt.Color(0, 0, 0));

        Nombre15.setBackground(new java.awt.Color(255, 255, 255));
        Nombre15.setForeground(new java.awt.Color(255, 255, 255));
        Nombre15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre15.setText("CÓDIGO:");

        javax.swing.GroupLayout btnNombre15Layout = new javax.swing.GroupLayout(btnNombre15);
        btnNombre15.setLayout(btnNombre15Layout);
        btnNombre15Layout.setHorizontalGroup(
            btnNombre15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre15Layout.setVerticalGroup(
            btnNombre15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 130, 30));

        TextId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextIdActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextId, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 200, 30));

        btnNombre.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre.setForeground(new java.awt.Color(0, 0, 0));

        Nombre.setBackground(new java.awt.Color(255, 255, 255));
        Nombre.setForeground(new java.awt.Color(255, 255, 255));
        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("PRIMER NOMBRE:");

        javax.swing.GroupLayout btnNombreLayout = new javax.swing.GroupLayout(btnNombre);
        btnNombre.setLayout(btnNombreLayout);
        btnNombreLayout.setHorizontalGroup(
            btnNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombreLayout.setVerticalGroup(
            btnNombreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 130, 30));

        TextPNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPNombreActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextPNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 200, 30));

        btnNombre1.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre1.setForeground(new java.awt.Color(0, 0, 0));

        Nombre1.setBackground(new java.awt.Color(255, 255, 255));
        Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre1.setText("SEGUNDO NOMBRE:");

        javax.swing.GroupLayout btnNombre1Layout = new javax.swing.GroupLayout(btnNombre1);
        btnNombre1.setLayout(btnNombre1Layout);
        btnNombre1Layout.setHorizontalGroup(
            btnNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre1Layout.setVerticalGroup(
            btnNombre1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 130, 30));

        TextSNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSNombreActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextSNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 200, 30));

        btnNombre2.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre2.setForeground(new java.awt.Color(0, 0, 0));

        Nombre2.setBackground(new java.awt.Color(255, 255, 255));
        Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        Nombre2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre2.setText("TERCER NOMBRE");

        javax.swing.GroupLayout btnNombre2Layout = new javax.swing.GroupLayout(btnNombre2);
        btnNombre2.setLayout(btnNombre2Layout);
        btnNombre2Layout.setHorizontalGroup(
            btnNombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre2Layout.setVerticalGroup(
            btnNombre2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 130, 30));

        TextTNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTNombreActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 200, 30));

        btnNombre3.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre3.setForeground(new java.awt.Color(0, 0, 0));

        Nombre3.setBackground(new java.awt.Color(255, 255, 255));
        Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        Nombre3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre3.setText("PRIMER APELLIDO");

        javax.swing.GroupLayout btnNombre3Layout = new javax.swing.GroupLayout(btnNombre3);
        btnNombre3.setLayout(btnNombre3Layout);
        btnNombre3Layout.setHorizontalGroup(
            btnNombre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre3Layout.setVerticalGroup(
            btnNombre3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre3, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 130, 30));

        TextPApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPApellidoActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextPApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 200, 30));

        btnNombre4.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre4.setForeground(new java.awt.Color(0, 0, 0));

        Nombre4.setBackground(new java.awt.Color(255, 255, 255));
        Nombre4.setForeground(new java.awt.Color(255, 255, 255));
        Nombre4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre4.setText("SEGUNDO APELLIDO");

        javax.swing.GroupLayout btnNombre4Layout = new javax.swing.GroupLayout(btnNombre4);
        btnNombre4.setLayout(btnNombre4Layout);
        btnNombre4Layout.setHorizontalGroup(
            btnNombre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre4Layout.setVerticalGroup(
            btnNombre4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre4, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 130, 30));

        TextSApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextSApellidoActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextSApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 200, 30));

        btnNombre5.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre5.setForeground(new java.awt.Color(0, 0, 0));

        Nombre5.setBackground(new java.awt.Color(255, 255, 255));
        Nombre5.setForeground(new java.awt.Color(255, 255, 255));
        Nombre5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre5.setText("TELÉFONO:");

        javax.swing.GroupLayout btnNombre5Layout = new javax.swing.GroupLayout(btnNombre5);
        btnNombre5.setLayout(btnNombre5Layout);
        btnNombre5Layout.setHorizontalGroup(
            btnNombre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre5Layout.setVerticalGroup(
            btnNombre5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre5, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 130, 30));

        TextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 200, 30));

        btnNombre6.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre6.setForeground(new java.awt.Color(0, 0, 0));

        Nombre6.setBackground(new java.awt.Color(255, 255, 255));
        Nombre6.setForeground(new java.awt.Color(255, 255, 255));
        Nombre6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre6.setText("CORREO:");

        javax.swing.GroupLayout btnNombre6Layout = new javax.swing.GroupLayout(btnNombre6);
        btnNombre6.setLayout(btnNombre6Layout);
        btnNombre6Layout.setHorizontalGroup(
            btnNombre6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre6Layout.setVerticalGroup(
            btnNombre6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre6, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 500, 130, 30));

        TextCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextCorreoActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 200, 30));

        btnNombre11.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre11.setForeground(new java.awt.Color(0, 0, 0));

        Nombre11.setBackground(new java.awt.Color(255, 255, 255));
        Nombre11.setForeground(new java.awt.Color(255, 255, 255));
        Nombre11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre11.setText("FECHA NACIMIENTO:");

        javax.swing.GroupLayout btnNombre11Layout = new javax.swing.GroupLayout(btnNombre11);
        btnNombre11.setLayout(btnNombre11Layout);
        btnNombre11Layout.setHorizontalGroup(
            btnNombre11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre11Layout.setVerticalGroup(
            btnNombre11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre11, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 130, 30));
        panelmpusuarios.add(JFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 540, 200, 30));

        btnNombre7.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre7.setForeground(new java.awt.Color(0, 0, 0));

        Nombre7.setBackground(new java.awt.Color(255, 255, 255));
        Nombre7.setForeground(new java.awt.Color(255, 255, 255));
        Nombre7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre7.setText("EMERGENCIA NOMBRE:");

        javax.swing.GroupLayout btnNombre7Layout = new javax.swing.GroupLayout(btnNombre7);
        btnNombre7.setLayout(btnNombre7Layout);
        btnNombre7Layout.setHorizontalGroup(
            btnNombre7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre7Layout.setVerticalGroup(
            btnNombre7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre7, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, 150, 30));

        TextPENombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPENombreActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextPENombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 200, 30));

        btnNombre8.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre8.setForeground(new java.awt.Color(0, 0, 0));

        Nombre8.setBackground(new java.awt.Color(255, 255, 255));
        Nombre8.setForeground(new java.awt.Color(255, 255, 255));
        Nombre8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre8.setText("EMERGENCIA APELLIDO:");

        javax.swing.GroupLayout btnNombre8Layout = new javax.swing.GroupLayout(btnNombre8);
        btnNombre8.setLayout(btnNombre8Layout);
        btnNombre8Layout.setHorizontalGroup(
            btnNombre8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre8Layout.setVerticalGroup(
            btnNombre8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre8, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 620, 150, 30));

        TextPEApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextPEApellidoActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextPEApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 200, 30));

        btnNombre9.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre9.setForeground(new java.awt.Color(0, 0, 0));

        Nombre9.setBackground(new java.awt.Color(255, 255, 255));
        Nombre9.setForeground(new java.awt.Color(255, 255, 255));
        Nombre9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre9.setText("PARENTESCO:");

        javax.swing.GroupLayout btnNombre9Layout = new javax.swing.GroupLayout(btnNombre9);
        btnNombre9.setLayout(btnNombre9Layout);
        btnNombre9Layout.setHorizontalGroup(
            btnNombre9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre9Layout.setVerticalGroup(
            btnNombre9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre9, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre9, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 660, 130, 30));

        TextParentesco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextParentescoActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextParentesco, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 660, 200, 30));

        btnNombre16.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre16.setForeground(new java.awt.Color(0, 0, 0));

        Nombre16.setBackground(new java.awt.Color(255, 255, 255));
        Nombre16.setForeground(new java.awt.Color(255, 255, 255));
        Nombre16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre16.setText("TELEFONO EMERGENCIA:");

        javax.swing.GroupLayout btnNombre16Layout = new javax.swing.GroupLayout(btnNombre16);
        btnNombre16.setLayout(btnNombre16Layout);
        btnNombre16Layout.setHorizontalGroup(
            btnNombre16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre16Layout.setVerticalGroup(
            btnNombre16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre16, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 700, 160, 30));

        TextTelefonoPE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextTelefonoPEActionPerformed(evt);
            }
        });
        panelmpusuarios.add(TextTelefonoPE, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 700, 200, 30));

        btnNombre13.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre13.setForeground(new java.awt.Color(0, 0, 0));

        Nombre13.setBackground(new java.awt.Color(255, 255, 255));
        Nombre13.setForeground(new java.awt.Color(255, 255, 255));
        Nombre13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre13.setText("FECHA PRÓX PAGO:");

        javax.swing.GroupLayout btnNombre13Layout = new javax.swing.GroupLayout(btnNombre13);
        btnNombre13.setLayout(btnNombre13Layout);
        btnNombre13Layout.setHorizontalGroup(
            btnNombre13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre13Layout.setVerticalGroup(
            btnNombre13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 780, 130, 30));
        panelmpusuarios.add(JFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 780, 200, 30));

        btnNombre12.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre12.setForeground(new java.awt.Color(0, 0, 0));

        Nombre12.setBackground(new java.awt.Color(255, 255, 255));
        Nombre12.setForeground(new java.awt.Color(255, 255, 255));
        Nombre12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre12.setText("FECHA INGRESO:");

        javax.swing.GroupLayout btnNombre12Layout = new javax.swing.GroupLayout(btnNombre12);
        btnNombre12.setLayout(btnNombre12Layout);
        btnNombre12Layout.setHorizontalGroup(
            btnNombre12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre12Layout.setVerticalGroup(
            btnNombre12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre12, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 740, 150, 30));
        panelmpusuarios.add(JFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 740, 200, 30));

        btnNombre10.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre10.setForeground(new java.awt.Color(0, 0, 0));

        Nombre10.setBackground(new java.awt.Color(255, 255, 255));
        Nombre10.setForeground(new java.awt.Color(255, 255, 255));
        Nombre10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre10.setText("FOTO:");

        javax.swing.GroupLayout btnNombre10Layout = new javax.swing.GroupLayout(btnNombre10);
        btnNombre10.setLayout(btnNombre10Layout);
        btnNombre10Layout.setHorizontalGroup(
            btnNombre10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre10Layout.setVerticalGroup(
            btnNombre10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre10, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 50, 30));

        javax.swing.GroupLayout pnlCamaraLayout = new javax.swing.GroupLayout(pnlCamara);
        pnlCamara.setLayout(pnlCamaraLayout);
        pnlCamaraLayout.setHorizontalGroup(
            pnlCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCamaraLayout.setVerticalGroup(
            pnlCamaraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelmpusuarios.add(pnlCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 350, 320));

        fotousuario.setPreferredSize(new java.awt.Dimension(436, 400));

        javax.swing.GroupLayout panelfotoLayout = new javax.swing.GroupLayout(panelfoto);
        panelfoto.setLayout(panelfotoLayout);
        panelfotoLayout.setHorizontalGroup(
            panelfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fotousuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );
        panelfotoLayout.setVerticalGroup(
            panelfotoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelfotoLayout.createSequentialGroup()
                .addComponent(fotousuario, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelmpusuarios.add(panelfoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 349, 320));

        btnNombre14.setBackground(new java.awt.Color(0, 0, 0));
        btnNombre14.setForeground(new java.awt.Color(0, 0, 0));

        Nombre14.setBackground(new java.awt.Color(255, 255, 255));
        Nombre14.setForeground(new java.awt.Color(255, 255, 255));
        Nombre14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre14.setText("BUSCAR POR:");

        javax.swing.GroupLayout btnNombre14Layout = new javax.swing.GroupLayout(btnNombre14);
        btnNombre14.setLayout(btnNombre14Layout);
        btnNombre14Layout.setHorizontalGroup(
            btnNombre14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        btnNombre14Layout.setVerticalGroup(
            btnNombre14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Nombre14, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnNombre14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 630, 130, 30));

        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        panelmpusuarios.add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 630, 380, 30));

        btnIngresar.setText("INGRESAR");
        btnIngresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarMouseClicked(evt);
            }
        });
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });
        panelmpusuarios.add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 630, 90, 30));

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLimpiarMouseClicked(evt);
            }
        });
        panelmpusuarios.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 630, 100, 30));

        btnModificarl.setText("MODIFICAR");
        btnModificarl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarlMouseClicked(evt);
            }
        });
        panelmpusuarios.add(btnModificarl, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 630, 100, 30));

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        panelmpusuarios.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 630, 90, 30));

        Tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tabla1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tabla1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla1);

        panelmpusuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 680, 950, 130));

        btniniciar.setBackground(new java.awt.Color(0, 0, 0));

        iniciar.setBackground(new java.awt.Color(255, 255, 255));
        iniciar.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        iniciar.setForeground(new java.awt.Color(255, 255, 255));
        iniciar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        iniciar.setText("INICIAR");

        btnliniciar.setBackground(new java.awt.Color(255, 255, 255));

        liniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes_orginal/liniciar1.png"))); // NOI18N
        liniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        liniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liniciarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                liniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                liniciarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnliniciarLayout = new javax.swing.GroupLayout(btnliniciar);
        btnliniciar.setLayout(btnliniciarLayout);
        btnliniciarLayout.setHorizontalGroup(
            btnliniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnliniciarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(liniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnliniciarLayout.setVerticalGroup(
            btnliniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnliniciarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(liniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout btniniciarLayout = new javax.swing.GroupLayout(btniniciar);
        btniniciar.setLayout(btniniciarLayout);
        btniniciarLayout.setHorizontalGroup(
            btniniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btniniciarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnliniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(iniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btniniciarLayout.setVerticalGroup(
            btniniciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(iniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnliniciar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btniniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 250, 220, 80));

        btnapagar.setBackground(new java.awt.Color(0, 0, 0));

        apagar.setBackground(new java.awt.Color(255, 255, 255));
        apagar.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        apagar.setForeground(new java.awt.Color(255, 255, 255));
        apagar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        apagar.setText("APAGAR");

        btnlapagar.setBackground(new java.awt.Color(0, 0, 0));

        lapagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes_orginal/lapagar1.png"))); // NOI18N
        lapagar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lapagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lapagarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lapagarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lapagarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnlapagarLayout = new javax.swing.GroupLayout(btnlapagar);
        btnlapagar.setLayout(btnlapagarLayout);
        btnlapagarLayout.setHorizontalGroup(
            btnlapagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnlapagarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnlapagarLayout.setVerticalGroup(
            btnlapagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnlapagarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lapagar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout btnapagarLayout = new javax.swing.GroupLayout(btnapagar);
        btnapagar.setLayout(btnapagarLayout);
        btnapagarLayout.setHorizontalGroup(
            btnapagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnapagarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnlapagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apagar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnapagarLayout.setVerticalGroup(
            btnapagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(apagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnlapagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnapagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 340, 220, 80));

        btncapturar.setBackground(new java.awt.Color(0, 0, 0));

        capturar.setBackground(new java.awt.Color(255, 255, 255));
        capturar.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        capturar.setForeground(new java.awt.Color(255, 255, 255));
        capturar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        capturar.setText("CAPTURAR");

        btnlcapturar.setBackground(new java.awt.Color(0, 0, 0));

        lcapturar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes_orginal/lcapturar1.png"))); // NOI18N
        lcapturar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lcapturar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lcapturarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lcapturarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lcapturarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnlcapturarLayout = new javax.swing.GroupLayout(btnlcapturar);
        btnlcapturar.setLayout(btnlcapturarLayout);
        btnlcapturarLayout.setHorizontalGroup(
            btnlcapturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnlcapturarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lcapturar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnlcapturarLayout.setVerticalGroup(
            btnlcapturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnlcapturarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lcapturar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout btncapturarLayout = new javax.swing.GroupLayout(btncapturar);
        btncapturar.setLayout(btncapturarLayout);
        btncapturarLayout.setHorizontalGroup(
            btncapturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btncapturarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnlcapturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(capturar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btncapturarLayout.setVerticalGroup(
            btncapturarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(capturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnlcapturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btncapturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 430, 220, 80));

        btnguardar.setBackground(new java.awt.Color(0, 0, 0));

        guardar.setBackground(new java.awt.Color(255, 255, 255));
        guardar.setFont(new java.awt.Font("Elephant", 0, 12)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        guardar.setText("GUARDAR");

        btnlguardar.setBackground(new java.awt.Color(0, 0, 0));

        lguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes_orginal/lguardar1.png"))); // NOI18N
        lguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lguardarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lguardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lguardarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnlguardarLayout = new javax.swing.GroupLayout(btnlguardar);
        btnlguardar.setLayout(btnlguardarLayout);
        btnlguardarLayout.setHorizontalGroup(
            btnlguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnlguardarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        btnlguardarLayout.setVerticalGroup(
            btnlguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnlguardarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout btnguardarLayout = new javax.swing.GroupLayout(btnguardar);
        btnguardar.setLayout(btnguardarLayout);
        btnguardarLayout.setHorizontalGroup(
            btnguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnguardarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnlguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        btnguardarLayout.setVerticalGroup(
            btnguardarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(guardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnlguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panelmpusuarios.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 520, 220, 80));

        lblNombreCamara.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreCamara.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNombreCamara.setText("-");
        panelmpusuarios.add(lblNombreCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 250, -1));
        panelmpusuarios.add(TextFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 240, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelmpusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 1536, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelmpusuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 1080, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MaximizarusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizarusuariosMouseClicked
        if (maximizado) {
            setExtendedState(JFrame.NORMAL); // Restaurar el tamaño normal
            maximizado = false;
        } else {
            setExtendedState(JFrame.MAXIMIZED_BOTH); // Maximizar
            maximizado = true;
        }
    }//GEN-LAST:event_MaximizarusuariosMouseClicked

    private void MaximizarusuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizarusuariosMouseEntered
        btnMaximizarusuarios.setBackground(new Color(204,204,204));
        Maximizarusuarios.setForeground(Color.black);
    }//GEN-LAST:event_MaximizarusuariosMouseEntered

    private void MaximizarusuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaximizarusuariosMouseExited
        btnMaximizarusuarios.setBackground(Color.white);
        Maximizarusuarios.setForeground(Color.black);
    }//GEN-LAST:event_MaximizarusuariosMouseExited

    private void SalirusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirusuariosMouseClicked
        System.exit(0);
    }//GEN-LAST:event_SalirusuariosMouseClicked

    private void SalirusuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirusuariosMouseEntered
        btnSalirusuarios.setBackground(Color.red);
        Salirusuarios.setForeground(Color.white);
    }//GEN-LAST:event_SalirusuariosMouseEntered

    private void SalirusuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirusuariosMouseExited
        btnSalirusuarios.setBackground(Color.white);
        Salirusuarios.setForeground(Color.black);
    }//GEN-LAST:event_SalirusuariosMouseExited

    private void MinimizarusuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarusuariosMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_MinimizarusuariosMouseClicked

    private void MinimizarusuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarusuariosMouseEntered
        btnMinimizarusuarios.setBackground(new Color(204,204,204));
        Minimizarusuarios.setForeground(Color.black);
    }//GEN-LAST:event_MinimizarusuariosMouseEntered

    private void MinimizarusuariosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MinimizarusuariosMouseExited
        btnMinimizarusuarios.setBackground(Color.white);
        Minimizarusuarios.setForeground(Color.black);
    }//GEN-LAST:event_MinimizarusuariosMouseExited

    private void panelsalirusuariosMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsalirusuariosMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelsalirusuariosMouseDragged

    private void panelsalirusuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelsalirusuariosMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_panelsalirusuariosMousePressed

    private void TextIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextIdActionPerformed

    private void TextPNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPNombreActionPerformed

    private void TextSNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSNombreActionPerformed

    private void TextTNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTNombreActionPerformed

    private void TextPApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPApellidoActionPerformed

    private void TextSApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextSApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextSApellidoActionPerformed

    private void TextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoActionPerformed

    private void TextCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextCorreoActionPerformed

    private void TextPENombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPENombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPENombreActionPerformed

    private void TextPEApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextPEApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextPEApellidoActionPerformed

    private void TextParentescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextParentescoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextParentescoActionPerformed

    private void TextTelefonoPEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextTelefonoPEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextTelefonoPEActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void btnIngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarMouseClicked
        UsuarioGimnasio g = new UsuarioGimnasio();
        g.InsertarUsuarios(TextPNombre, TextSNombre, TextTNombre, TextPApellido, TextSApellido, TextTelefono, TextCorreo, TextPENombre, TextPEApellido, TextParentesco, TextFoto, JFechaNacimiento, JFechaIngreso, JFechaPago, TextTelefonoPE);
        g.MostrarUsuarios(Tabla1);
    }//GEN-LAST:event_btnIngresarMouseClicked

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void btnModificarlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarlMouseClicked
        UsuarioGimnasio usuarioGimnasio = new UsuarioGimnasio();

        String NuevoId = TextId.getText();
        String NuevoPNombre = TextPNombre.getText();
        String NuevoSNombre = TextSNombre.getText();
        String NuevoTNombre = TextTNombre.getText();
        String NuevoPApellido = TextPApellido.getText();
        String NuevoSApellido = TextSApellido.getText();
        String NuevoTelefono = TextTelefono.getText();
        String NuevoCorreo = TextCorreo.getText();
        String NuevopersonaEmergenciaNombre = TextPENombre.getText();
        String NuevopersonaEmergenciaApellido = TextPEApellido.getText();
        String NuevoParentesco = TextParentesco.getText();
        String NuevoFoto = TextFoto.getText();
        String NuevotelefonoPE = TextTelefonoPE.getText();

        Date NuevofechaNacimiento = (JFechaNacimiento != null && JFechaNacimiento.getDate() != null)
                ? JFechaNacimiento.getDate()
                : null;
        Date NuevofechaIngreso = (JFechaIngreso != null && JFechaIngreso.getDate() != null)
                ? JFechaIngreso.getDate()
                : null;
        Date NuevoJFechaPago = (JFechaPago != null && JFechaPago.getDate() != null)
                ? JFechaPago.getDate()
                : null;

        if (!NuevoId.isEmpty() && !NuevoPNombre.isEmpty() && !NuevoSNombre.isEmpty() && !NuevoTNombre.isEmpty()
                && !NuevoPApellido.isEmpty() && !NuevoSApellido.isEmpty() && !NuevoTelefono.isEmpty()
                && !NuevoCorreo.isEmpty() && !NuevopersonaEmergenciaNombre.isEmpty() && !NuevopersonaEmergenciaApellido.isEmpty()
                && !NuevoParentesco.isEmpty() && !NuevotelefonoPE.isEmpty() && NuevofechaNacimiento != null
                && NuevofechaIngreso != null && NuevoJFechaPago != null) {

            usuarioGimnasio.ModificarUsuarios(NuevoId, NuevoPNombre, NuevoSNombre, NuevoTNombre, NuevoPApellido,
                    NuevoSApellido, NuevoTelefono, NuevoCorreo, NuevopersonaEmergenciaNombre,
                    NuevopersonaEmergenciaApellido, NuevoParentesco, NuevoFoto, JFechaNacimiento, JFechaIngreso,
                    JFechaPago, NuevotelefonoPE);

            JOptionPane.showMessageDialog(null, "SE PUDO MODIFICAR EL USUARIO", "MODIFICADO", JOptionPane.PLAIN_MESSAGE);
            usuarioGimnasio.MostrarUsuarios(Tabla1);
        } else {
            JOptionPane.showMessageDialog(null, "NO SE PUDO MODIFICAR EL USUARIO. Verifica que todos los campos obligatorios estén llenos.", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarlMouseClicked

    private Date parseFecha(String fechaStr, SimpleDateFormat dateFormat) {
        try {
            if (!fechaStr.isEmpty()) {
                return dateFormat.parse(fechaStr);
            } else {
                return null;
            }
        } catch (ParseException e) {
            System.err.println("Error al parsear la fecha: " + fechaStr);
            e.printStackTrace();
            return null;
        }
    }

    private String obtenerValorCelda(TableModel modelo, int fila, int columna) {
        try {
            Object valor = modelo.getValueAt(fila, columna);
            return (valor != null) ? valor.toString() : "";
        } catch (Exception e) {
            System.err.println("Error al obtener el valor de la celda: " + e.getMessage());
            e.printStackTrace();
            return "";
        }
    }

    private Date obtenerFechaCelda(TableModel modelo, int fila, int columna, SimpleDateFormat dateFormat) {
        String fechaStr = obtenerValorCelda(modelo, fila, columna);
        return parseFecha(fechaStr, dateFormat);
    }
    
    private void Tabla1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tabla1MouseClicked
        int index = Tabla1.getSelectedRow();
        if (index >= 0) {
            TableModel modelo = Tabla1.getModel();

            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");

            // Obtener datos de la tabla
            String pid = obtenerValorCelda(modelo, index, 0);
            String pnombre = obtenerValorCelda(modelo, index, 1);
            String snombre = obtenerValorCelda(modelo, index, 2);
            String tnombre = obtenerValorCelda(modelo, index, 3);
            String papellido = obtenerValorCelda(modelo, index, 4);
            String sapellido = obtenerValorCelda(modelo, index, 5);
            String telefono = obtenerValorCelda(modelo, index, 6);
            String correo = obtenerValorCelda(modelo, index, 7);
            String penombre = obtenerValorCelda(modelo, index, 8);
            String peapellido = obtenerValorCelda(modelo, index, 9);
            String parentesco = obtenerValorCelda(modelo, index, 10);
            String pfoto = obtenerValorCelda(modelo, index, 11);

            // Obtener fechas de la tabla
            Date fechaNacimiento = obtenerFechaCelda(modelo, index, 12, dateFormat);
            Date fechaIngreso = obtenerFechaCelda(modelo, index, 13, dateFormat);
            Date fechaProximaPago = obtenerFechaCelda(modelo, index, 14, dateFormat);

            String telefonoPE = obtenerValorCelda(modelo, index, 15);

            // Verificar si las fechas son válidas antes de asignarlas
            if (fechaNacimiento != null && fechaIngreso != null && fechaProximaPago != null) {
                // Establecer los valores en los JTextField
                TextId.setText(pid);
                TextPNombre.setText(pnombre);
                TextSNombre.setText(snombre);
                TextTNombre.setText(tnombre);
                TextPApellido.setText(papellido);
                TextSApellido.setText(sapellido);
                TextTelefono.setText(telefono);
                TextCorreo.setText(correo);
                TextPENombre.setText(penombre);
                TextPEApellido.setText(peapellido);
                TextParentesco.setText(parentesco);
                JFechaNacimiento.setDate(fechaNacimiento);
                JFechaIngreso.setDate(fechaIngreso);
                JFechaPago.setDate(fechaProximaPago);
                TextTelefonoPE.setText(telefonoPE);
                // Mostrar la foto en el JLabel
                mostrarFotoEnJLabel(pfoto, fotousuario);

            } else {
                // Manejar el caso en que alguna fecha no sea válida
                JOptionPane.showMessageDialog(null, "Al menos una de las fechas en la tabla no es válida.\n"
                    + "Fecha de Nacimiento: " + obtenerValorCelda(modelo, index, 10) + "\n"
                    + "Fecha de Ingreso: " + obtenerValorCelda(modelo, index, 11) + "\n"
                    + "Fecha de Próximo Pago: " + obtenerValorCelda(modelo, index, 12),
                    "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_Tabla1MouseClicked
 
    //Método para obtener la URL osea la extensión de la foto y mostrarla según las dimensiones del JLabel en el form
    private void mostrarFotoEnJLabel(String rutaFoto, JLabel JFoto) {
        if (rutaFoto != null && !rutaFoto.isEmpty()) {
            try {
                BufferedImage imagen = ImageIO.read(new File(rutaFoto));

                // Obtén las dimensiones del JLabel
                int anchoJLabel = JFoto.getWidth();
                int altoJLabel = JFoto.getHeight();

                // Redimensiona la imagen
                Image imagenRedimensionada = imagen.getScaledInstance(anchoJLabel, altoJLabel, Image.SCALE_SMOOTH);

                // Crea un ImageIcon con la imagen redimensionada
                ImageIcon iconoRedimensionado = new ImageIcon(imagenRedimensionada);

                // Asigna el ImageIcon al JLabel
                JFoto.setIcon(iconoRedimensionado);
            } catch (IOException e) {
                JOptionPane.showMessageDialog(null, "Error al cargar la imagen, ERROR: " + e.toString(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Limpiar el JLabel si no hay ruta de imagen
            JFoto.setIcon(null);
        }
    }

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void liniciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liniciarMouseClicked
        textoBotonesCuandoCargaCamara();

        Thread hilo = new Thread(){
            @Override
            public void run(){
                webcamPanel.start();
                PrenderBotones();
                textoBotonesCuandoCargoCamara();

            }
        };

        hilo.setDaemon(true);
        hilo.start();
        liniciar.setEnabled(false);

    }//GEN-LAST:event_liniciarMouseClicked

    private void liniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liniciarMouseEntered
        ImageIcon im = new ImageIcon("C:\\Users\\accpm\\OneDrive\\Escritorio\\ARCHIVOS_EXPORTADOS\\ICONOS\\liniciar2.png");
        liniciar.setIcon(im);
    }//GEN-LAST:event_liniciarMouseEntered

    private void liniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liniciarMouseExited
        ImageIcon im = new ImageIcon("C:\\Users\\accpm\\OneDrive\\Escritorio\\ARCHIVOS_EXPORTADOS\\ICONOS\\liniciar1.png");
        liniciar.setIcon(im);
    }//GEN-LAST:event_liniciarMouseExited

    private void lapagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lapagarMouseClicked
        webcamPanel.stop();
        ApagarBotones();
        liniciar.setEnabled(true);

    }//GEN-LAST:event_lapagarMouseClicked

    private void lapagarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lapagarMouseEntered
        ImageIcon im = new ImageIcon("C:\\Users\\accpm\\OneDrive\\Escritorio\\ARCHIVOS_EXPORTADOS\\ICONOS\\lapagar2.png");
        lapagar.setIcon(im);
    }//GEN-LAST:event_lapagarMouseEntered

    private void lapagarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lapagarMouseExited
        ImageIcon im = new ImageIcon("C:\\Users\\accpm\\OneDrive\\Escritorio\\ARCHIVOS_EXPORTADOS\\ICONOS\\lapagar1.png");
        lapagar.setIcon(im);
    }//GEN-LAST:event_lapagarMouseExited

    private void lcapturarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcapturarMouseClicked
        lcapturar.setText("Tomar otra foto");
        lguardar.setEnabled(true);

        ImageIcon foto;
        foto = new ImageIcon(webcam.getImage());
        Icon iconofoto = new ImageIcon(foto.getImage().getScaledInstance(fotousuario.getWidth(), fotousuario.getHeight(), Image.SCALE_SMOOTH));
        fotousuario.setIcon(iconofoto);

        ruta = webcam.getImage();

    }//GEN-LAST:event_lcapturarMouseClicked

    private void lcapturarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcapturarMouseEntered
        ImageIcon im = new ImageIcon("C:\\Users\\accpm\\OneDrive\\Escritorio\\ARCHIVOS_EXPORTADOS\\ICONOS\\lcapturar2.png");
        lcapturar.setIcon(im);
    }//GEN-LAST:event_lcapturarMouseEntered

    private void lcapturarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lcapturarMouseExited
        ImageIcon im = new ImageIcon("C:\\Users\\accpm\\OneDrive\\Escritorio\\ARCHIVOS_EXPORTADOS\\ICONOS\\lcapturar1.png");
        lcapturar.setIcon(im);
    }//GEN-LAST:event_lcapturarMouseExited

    private void lguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lguardarMouseClicked
        UsuarioGimnasio g = new UsuarioGimnasio();
        g.GuardarExtensionFoto(ruta, TextFoto);

        fotousuario.setIcon(null);
        lguardar.setEnabled(false);
        lcapturar.setText("CAPTURAR");

    }//GEN-LAST:event_lguardarMouseClicked

    private void lguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lguardarMouseEntered
        ImageIcon im = new ImageIcon("C:\\Users\\accpm\\OneDrive\\Escritorio\\ARCHIVOS_EXPORTADOS\\ICONOS\\lguardar2.png");
        lguardar.setIcon(im);
    }//GEN-LAST:event_lguardarMouseEntered

    private void lguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lguardarMouseExited
        ImageIcon im = new ImageIcon("C:\\Users\\accpm\\OneDrive\\Escritorio\\ARCHIVOS_EXPORTADOS\\ICONOS\\lguardar1.png");
        lguardar.setIcon(im);
    }//GEN-LAST:event_lguardarMouseExited

    private void btnLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLimpiarMouseClicked
        TextId.setText("");
        TextPNombre.setText("");
        TextSNombre.setText("");
        TextTNombre.setText("");
        TextPApellido.setText("");
        TextSApellido.setText("");
        TextTelefono.setText("");
        TextCorreo.setText("");
        JFechaNacimiento.setDate(null);
        TextPENombre.setText("");
        TextPEApellido.setText("");
        TextParentesco.setText("");
        fotousuario.setIcon(null);
        TextTelefonoPE.setText("");
        JFechaIngreso.setDate(null);
        JFechaPago.setDate(null);
    }//GEN-LAST:event_btnLimpiarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {
            int index = Tabla1.getSelectedRow();

            if (index >= 0) {
                TableModel modelo = Tabla1.getModel();
                String id = modelo.getValueAt(index, 0).toString();

                UsuarioGimnasio g = new UsuarioGimnasio();
                g.EliminarUsuario(id);

                g.MostrarUsuarios(Tabla1);
            } else {
                JOptionPane.showMessageDialog(null, "Por favor selecciona un registro para eliminar de la tabla.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocurrió un error al intentar eliminar el registro: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD_Gimnasio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD_Gimnasio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD_Gimnasio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD_Gimnasio1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD_Gimnasio1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Buscar;
    private com.toedter.calendar.JDateChooser JFechaIngreso;
    private com.toedter.calendar.JDateChooser JFechaNacimiento;
    private com.toedter.calendar.JDateChooser JFechaPago;
    private javax.swing.JLabel Maximizarusuarios;
    private javax.swing.JLabel Minimizarusuarios;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre10;
    private javax.swing.JLabel Nombre11;
    private javax.swing.JLabel Nombre12;
    private javax.swing.JLabel Nombre13;
    private javax.swing.JLabel Nombre14;
    private javax.swing.JLabel Nombre15;
    private javax.swing.JLabel Nombre16;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JLabel Nombre4;
    private javax.swing.JLabel Nombre5;
    private javax.swing.JLabel Nombre6;
    private javax.swing.JLabel Nombre7;
    private javax.swing.JLabel Nombre8;
    private javax.swing.JLabel Nombre9;
    private javax.swing.JLabel Salirusuarios;
    private javax.swing.JTable Tabla1;
    private javax.swing.JTextField TextCorreo;
    private javax.swing.JTextField TextFoto;
    private javax.swing.JTextField TextId;
    private javax.swing.JTextField TextPApellido;
    private javax.swing.JTextField TextPEApellido;
    private javax.swing.JTextField TextPENombre;
    private javax.swing.JTextField TextPNombre;
    private javax.swing.JTextField TextParentesco;
    private javax.swing.JTextField TextSApellido;
    private javax.swing.JTextField TextSNombre;
    private javax.swing.JTextField TextTNombre;
    private javax.swing.JTextField TextTelefono;
    private javax.swing.JTextField TextTelefonoPE;
    private javax.swing.JLabel apagar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JPanel btnMaximizarusuarios;
    private javax.swing.JPanel btnMinimizarusuarios;
    private javax.swing.JButton btnModificarl;
    private javax.swing.JPanel btnNombre;
    private javax.swing.JPanel btnNombre1;
    private javax.swing.JPanel btnNombre10;
    private javax.swing.JPanel btnNombre11;
    private javax.swing.JPanel btnNombre12;
    private javax.swing.JPanel btnNombre13;
    private javax.swing.JPanel btnNombre14;
    private javax.swing.JPanel btnNombre15;
    private javax.swing.JPanel btnNombre16;
    private javax.swing.JPanel btnNombre2;
    private javax.swing.JPanel btnNombre3;
    private javax.swing.JPanel btnNombre4;
    private javax.swing.JPanel btnNombre5;
    private javax.swing.JPanel btnNombre6;
    private javax.swing.JPanel btnNombre7;
    private javax.swing.JPanel btnNombre8;
    private javax.swing.JPanel btnNombre9;
    private javax.swing.JPanel btnSalirusuarios;
    private javax.swing.JPanel btnapagar;
    private javax.swing.JPanel btncapturar;
    private javax.swing.JPanel btnguardar;
    private javax.swing.JPanel btniniciar;
    private javax.swing.JPanel btnlapagar;
    private javax.swing.JPanel btnlcapturar;
    private javax.swing.JPanel btnlguardar;
    private javax.swing.JPanel btnliniciar;
    private javax.swing.JLabel capturar;
    public javax.swing.JLabel fotousuario;
    private javax.swing.JLabel guardar;
    private javax.swing.JLabel iniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lapagar;
    private javax.swing.JLabel lblNombreCamara;
    private javax.swing.JLabel lcapturar;
    private javax.swing.JLabel lguardar;
    private javax.swing.JLabel liniciar;
    private javax.swing.JPanel panelfoto;
    private javax.swing.JPanel panelmpusuarios;
    private javax.swing.JPanel panelsalirusuarios;
    public javax.swing.JPanel pnlCamara;
    // End of variables declaration//GEN-END:variables
}
